name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정 실행
  push:
    branches: [ main ]
  workflow_dispatch: # 수동 실행 가능
jobs:
  generate:
    permissions:
      contents: write # 쓰기 권한 명시
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Cassiiopeia
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug file creation
        run: |
          echo "Listing files in workspace:"
          ls -la
          echo "Listing files in dist/ (if exists):"
          ls -la dist/ || true
          echo "Listing files in output/ (if exists):"
          ls -la output/ || true
      - name: Push to output branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout output || git checkout -b output
          mkdir -p output
          mv output/github-contribution-grid-snake*.svg output/ || true
          git add output/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update snake animation"
            git push origin output --force
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
