# 잔디먹는 뱀 애니메이션 생성 워크플로우

name: generate animation

on:
  # 매 24시간마다 자동 실행
  schedule:
    - cron: "0 0 * * *"

  # 수동으로도 실행할 수 있도록 허용
  workflow_dispatch:

  # main 브랜치에 푸시되었을 때도 실행
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 1) GitHub 기여 그래프를 기반으로 SVG 애니메이션 생성
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Cassiiopeia
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 2) 생성된 SVG 파일을 output 브랜치에 푸시
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
