name: SUH-WAKA-README

on:
  schedule:
    # 스케줄
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  pull-requests: read
  issues: read

jobs:
  update-readme:
    name: suh-update-readme-metrics
    runs-on: ubuntu-latest
    steps:
      - name: waka-stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets._GITHUB_PAT_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_OS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SECTION_NAME: "waka"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "suh updated dev metrics"
          COMMIT_SINGLE: "False"
          LOCALE: "en"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          SYMBOL_VERSION: "1"
